import type { ProviderId } from "@lcs/core";

/**
 * Where a problem in the queue should open.
 *
 * Everything in this system is keyed by LeetCode slug, because that's the join key both
 * providers agree on. NeetCode's *pages*, however, live under its own renamed slugs —
 * `two-sum` is served at `/problems/two-integer-sum`. `data/neetcode-slugs.json` carries
 * that translation, generated by `pnpm neetcode:map`.
 *
 * NeetCode publishes problem pages for roughly 590 of LeetCode's 4,000-odd problems, so
 * resolution always falls back to LeetCode rather than inventing a URL that 404s.
 */

export interface NeetcodeSlugData {
  /** When `build:neetcode-map` last regenerated the file; null if it never has. */
  generatedAt: string | null;
  /** LeetCode slug -> NeetCode slug, for problems NeetCode has a page for. */
  bySlug: Record<string, string>;
}

export interface ResolvedLink {
  href: string;
  /** Which site the link actually points at — not always the one asked for. */
  site: ProviderId;
  /** True when NeetCode was preferred but has no page for this problem. */
  fellBack: boolean;
}

export interface ProblemLinks {
  readonly generatedAt: string | null;
  /** How many problems have a NeetCode page. */
  readonly size: number;
  /** NeetCode's slug for a LeetCode slug, or null when NeetCode doesn't host it. */
  neetcodeSlug(slug: string): string | null;
  /**
   * The reverse: LeetCode's slug for a NeetCode one.
   *
   * NeetCode's submission records identify problems by its own slug, so this is the join
   * that lets those become events keyed the way everything else is.
   */
  leetcodeSlug(neetcodeSlug: string): string | null;
  resolve(slug: string, prefer: ProviderId): ResolvedLink;
}

export function leetcodeUrl(slug: string): string {
  return `https://leetcode.com/problems/${slug}/`;
}

export function neetcodeUrl(neetcodeSlug: string): string {
  return `https://neetcode.io/problems/${neetcodeSlug}`;
}

export function createProblemLinks(data: NeetcodeSlugData): ProblemLinks {
  const bySlug = new Map(Object.entries(data.bySlug ?? {}));

  const neetcodeSlug = (slug: string) => bySlug.get(slug) ?? null;

  // Built once rather than scanned per lookup: a NeetCode sync translates a slug for
  // every submission it reads, which is thousands of calls on a first sync.
  const byNeetcodeSlug = new Map([...bySlug].map(([lc, nc]) => [nc, lc]));

  return {
    generatedAt: data.generatedAt ?? null,
    size: bySlug.size,
    neetcodeSlug,
    leetcodeSlug: (nc) => byNeetcodeSlug.get(nc) ?? null,
    resolve(slug, prefer) {
      if (prefer === "neetcode") {
        const nc = neetcodeSlug(slug);
        if (nc) return { href: neetcodeUrl(nc), site: "neetcode", fellBack: false };
        return { href: leetcodeUrl(slug), site: "leetcode", fellBack: true };
      }
      return { href: leetcodeUrl(slug), site: "leetcode", fellBack: false };
    },
  };
}

/** An empty map, so a missing or unreadable data file degrades to LeetCode links. */
export const EMPTY_PROBLEM_LINKS: NeetcodeSlugData = { generatedAt: null, bySlug: {} };
